# Generated by Django 5.1 on 2024-09-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
