# Generated by Django 5.1 on 2024-10-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='Intellabiz', max_length=100),
        ),
    ]
