# Generated by Django 5.1 on 2024-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='code_snippet',
        ),
        migrations.AddField(
            model_name='workflow',
            name='bash_command',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='python_code_snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
