# Generated by Django 5.1 on 2024-11-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_remove_workflow_code_snippet_workflow_bash_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='container_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
